Course Bur3r: schedule_maker.h File Reference
schedule_maker.h File Reference
#include <vector>
#include <string>
#include "course.h"
#include "schedule.h"
Functions
Schedule make_schedule (vector< string >)
void make_schedule (std::vector< Section > all_sections)
std::vector< Schedule > make_schedule (std::vector< Section > all_sections, std::map< std::string, std::vector< std::string >> required_courses_, int num_sections_, std::string preferred_start_time, std::string preferred_end_time, std::string preferred_padding)
int time_diff_in_minutes (std::string start, std::string end)
bool time_conflict (std::string start_one, std::string end_one, std::string start_two, std::string end_two, std::string preferred_padding)
Function Documentation
make_schedule() [1/3]
Schedule make_schedule (vector< string >)
helper function to generate the schedule
Parameters
vector<string>
Returns
Schedule object
make_schedule() [2/3]
void make_schedule (std::vector< Section > all_sections)
Test function to generate the schedules
Parameters
vector<Section> vector of all sections from all given courses
make_schedule() [3/3]
std::vector<Schedule> make_schedule (std::vector< Section > all_sections, std::map< std::string, std::vector< std::string >> required_courses_, int num_sections_, std::string preferred_start_time, std::string preferred_end_time, std::string preferred_padding)
Schedule maker function using sections and checking for required courses
Parameters
vector<Section> vector of Sections
map<string,vector<string>> map of required courses and required section types?
int number of sections needed for the schedule to be complete
string string containing the preferred start time for all courses and sections
string string containing the preferred end time for all courses and sections
Returns
vector holding all schedules made
time_diff_in_minutes()
int time_diff_in_minutes (std::string start, std::string end)
Helper function for time_conflict function. Calculates the time difference in minutes to help satisfy user's padding requirement.
Parameters
time1 start time
time2 end time
Returns
time difference
Definition at line 127 of file schedule_maker.cpp.
{
   int hours_start = stoi(start.substr(0, 2));
   int hours_end = stoi(end.substr(0, 2));
   int minutes_start = stoi(start.substr(3, 2));
   int minutes_end = stoi(end.substr(3, 2));
   int total_minutes_start = hours_start * 60 + minutes_start;
   int total_minutes_end = hours_end * 60 + minutes_end;
   return abs(total_minutes_start - total_minutes_end);
 }
Referenced by time_conflict().
time_conflict()
bool time_conflict (std::string start_one, std::string end_one, std::string start_two, std::string end_two, std::string preferred_padding)
Function to check whether section times overlap
Parameters
string start time for first section
string end time for first section
string start time for second section
string end time for second section
Returns
true if conflict, false if no conflict
Definition at line 139 of file schedule_maker.cpp.
{
   int padding_minutes = time_diff_in_minutes("00:00", preferred_padding);
   int end_one_minutes = time_diff_in_minutes("00:00", end_one);
   int start_two_minutes = time_diff_in_minutes("00:00", start_two);
   if (start_one <= start_two && end_one_minutes + padding_minutes >= start_two_minutes ||
       start_two <= start_one && end_two >= end_one) {
     return true;
   } else {
     return false;
   }
 }
References time_diff_in_minutes().
Referenced by make_schedule().