main: main.cpp schedule.cpp schedule.h course.cpp course.h section.cpp section.h json_parser.cpp json_parser.h schedule_maker.cpp schedule_maker.h
	g++ -std=c++20 -o main main.cpp -I. -I cget/include
