name: C/C++ CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install build-essential
        run: sudo apt install -y build-essential
      - name: make
        run: cd backend && mkdir build && make
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: build/main
