name: Build and Deploy Website via SSH

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Edit permission
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chown -R github:github ${{ secrets.REMOTE_WEBROOT }}
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chmod -R 755 ${{ secrets.REMOTE_WEB }}

    - name: Deploy via SCP
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          source: "frontend/website/"
          target: "${{ secrets.REMOTE_DIR }}"

    - name: restart nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chown -R www-data:www-data ${{ secrets.REMOTE_WEBROOT }}
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S chmod -R 755 ${{ secrets.REMOTE_WEBROOT }}
            echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart nginx
